<?php

 $apiKey = "rzp_test_RO6LczzcnH3lHC";

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<form action="../homepage.html" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="1000" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="100"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="BookCabin"
    data-description="Bakery"
    data-image="http://localhost/personal/logo.png"
    data-prefill.name="Alex"
    data-prefill.email="alex@gmail.com"
    data-prefill.contact="8904300710"
    data-theme.color="#F37256f"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<style>
    .razorpay-payment-button { display:none; }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('.razorpay-payment-button').click();

    });
    </script>